from turtle import Turtle, Screen

timmy = Turtle()
timmy.shape("turtle")
timmy.color("aqua")
timmy.forward(200)
timmy.right(90)
timmy.forward(200)
timmy.right(90)
timmy.forward(200)
timmy.right(90)
timmy.forward(200)
timmy.right(90)
screen = Screen()
screen.title('Olá mundo')
screen.exitonclick()
